// Generated by CoffeeScript 1.8.0
(function() {
  'use-strict';
  $(document).ready(function() {
    var pgwbrowser;
    pgwbrowser = $.pgwbrowser();
    console.log(pgwbrowser);
  });

}).call(this);
