// Generated by CoffeeScript 1.8.0
(function() {
  'use-strict';
  $(document).ready(function() {
    var isIE, pgwBrowser;
    pgwBrowser = $.pgwBrowser();
    console.log(pgwBrowser);
    isIE = pgwBrowser['browser']['group'] === 'Explorer' ? true : false;
    if (isIE) {
      $('.site-wrapper').addClass('ie');
    }
  });

}).call(this);
