<?php
/*
 * Function to register a new field for user's country
 *
 * @since 2.2.28
 * @returns void
 */

function ninja_forms_register_field_country(){
	$countries = array(
		__( '- Seleccione', 'ninja-forms' ) => '',
		__( 'Afganistán', 'ninja-forms' ) => 'AF',
		__( 'Albania', 'ninja-forms' ) => 'AL',
		__( 'Argelia', 'ninja-forms' ) => 'DZ',
		__( 'Samoa Americana', 'ninja-forms' ) => 'AS',
		__( 'Andorra', 'ninja-forms' ) => 'AD',
		__( 'Angola', 'ninja-forms' ) => 'AO',
		__( 'Anguila', 'ninja-forms' ) => 'AI',
		__( 'Antártida', 'ninja-forms' ) => 'AQ',
		__( 'Antigua y Barbuda', 'ninja-forms' ) => 'AG',
		__( 'Argentina', 'ninja-forms' ) => 'AR',
		__( 'Armenia', 'ninja-forms' ) => 'AM',
		__( 'Aruba', 'ninja-forms' ) => 'AW',
		__( 'Australia', 'ninja-forms' ) => 'AU',
		__( 'Austria', 'ninja-forms' ) => 'AT',
		__( 'Azerbaiyán', 'ninja-forms' ) => 'AZ',
		__( 'Bahamas', 'ninja-forms' ) => 'BS',
		__( 'Bahrein', 'ninja-forms' ) => 'BH',
		__( 'Bangladesh', 'ninja-forms' ) => 'BD',
		__( 'Barbados', 'ninja-forms' ) => 'BB',
		__( 'Bielorrusia', 'ninja-forms' ) => 'BY',
		__( 'Bélgica', 'ninja-forms' ) => 'BE',
		__( 'Belice', 'ninja-forms' ) => 'BZ',
		__( 'Benin', 'ninja-forms' ) => 'BJ',
		__( 'Bermuda', 'ninja-forms' ) => 'BM',
		__( 'Bután', 'ninja-forms' ) => 'BT',
		__( 'Bolivia', 'ninja-forms' ) => 'BO',
		__( 'Bosnia y Herzegovina', 'ninja-forms' ) => 'BA',
		__( 'Botswana', 'ninja-forms' ) => 'BW',
		__( 'Isla Bouvet', 'ninja-forms' ) => 'BV',
		__( 'Brasil', 'ninja-forms' ) => 'BR',
		__( 'Territorio Británico del Océano Índico', 'ninja-forms' ) => 'IO',
		__( 'Brunei Darussalam', 'ninja-forms' ) => 'BN',
		__( 'Bulgaria', 'ninja-forms' ) => 'BG',
		__( 'Burkina Faso', 'ninja-forms' ) => 'BF',
		__( 'Burundi', 'ninja-forms' ) => 'BI',
		__( 'Camboya', 'ninja-forms' ) => 'KH',
		__( 'Camerún', 'ninja-forms' ) => 'CM',
		__( 'Canadá', 'ninja-forms' ) => 'CA',
		__( 'Cabo Verde', 'ninja-forms' ) => 'CV',
		__( 'Islas Caimán', 'ninja-forms' ) => 'KY',
		__( 'República Centroafricana', 'ninja-forms' ) => 'CF',
		__( 'Chad', 'ninja-forms' ) => 'TD',
		__( 'Chile', 'ninja-forms' ) => 'CL',
		__( 'China', 'ninja-forms' ) => 'CN',
		__( 'Isla de Navidad', 'ninja-forms' ) => 'CX',
		__( 'Cocos (Keeling) Islands', 'ninja-forms' ) => 'CC',
		__( 'Colombia', 'ninja-forms' ) => 'CO',
		__( 'Comoras', 'ninja-forms' ) => 'KM',
		__( 'Congo', 'ninja-forms' ) => 'CG',
		__( 'La República Democrática del Congo', 'ninja-forms' ) => 'CD',
		__( 'Islas Cook', 'ninja-forms' ) => 'CK',
		__( 'Costa Rica', 'ninja-forms' ) => 'CR',
		__( 'Costa de Marfil', 'ninja-forms' ) => 'CI',
		__( 'Croacia', 'ninja-forms' ) => 'HR',
		__( 'Cuba', 'ninja-forms' ) => 'CU',
		__( 'Chipre', 'ninja-forms' ) => 'CY',
		__( 'República Checa', 'ninja-forms' ) => 'CZ',
		__( 'Dinamarca', 'ninja-forms' ) => 'DK',
		__( 'Djibouti', 'ninja-forms' ) => 'DJ',
		__( 'Dominica', 'ninja-forms' ) => 'DM',
		__( 'República Dominicana', 'ninja-forms' ) => 'DO',
		__( 'Timor Oriental', 'ninja-forms' ) => 'TL',
		__( 'Ecuador', 'ninja-forms' ) => 'EC',
		__( 'Egipto', 'ninja-forms' ) => 'EG',
		__( 'El Salvador', 'ninja-forms' ) => 'SV',
		__( 'Guinea Ecuatorial', 'ninja-forms' ) => 'GQ',
		__( 'Eritrea', 'ninja-forms' ) => 'ER',
		__( 'Estonia', 'ninja-forms' ) => 'EE',
		__( 'Etiopía', 'ninja-forms' ) => 'ET',
		__( 'Islas Malvinas', 'ninja-forms' ) => 'FK',
		__( 'Islas Feroe', 'ninja-forms' ) => 'FO',
		__( 'Fiji', 'ninja-forms' ) => 'FJ',
		__( 'Finlandia', 'ninja-forms' ) => 'FI',
		__( 'Francia', 'ninja-forms' ) => 'FR',
		__( 'Guayana francés', 'ninja-forms' ) => 'GF',
		__( 'Polinesia francés', 'ninja-forms' ) => 'PF',
		__( 'Territorios Franceses del Sur', 'ninja-forms' ) => 'TF',
		__( 'Gabón', 'ninja-forms' ) => 'GA',
		__( 'Gambia', 'ninja-forms' ) => 'GM',
		__( 'Georgia', 'ninja-forms' ) => 'GE',
		__( 'Alemania', 'ninja-forms' ) => 'DE',
		__( 'Ghana', 'ninja-forms' ) => 'GH',
		__( 'Gibraltar', 'ninja-forms' ) => 'GI',
		__( 'Grecia', 'ninja-forms' ) => 'GR',
		__( 'Groenlandia', 'ninja-forms' ) => 'GL',
		__( 'Granada', 'ninja-forms' ) => 'GD',
		__( 'Guadeloupe', 'ninja-forms' ) => 'GP',
		__( 'Guam', 'ninja-forms' ) => 'GU',
		__( 'Guatemala', 'ninja-forms' ) => 'GT',
		__( 'Guinea', 'ninja-forms' ) => 'GN',
		__( 'Guinea-Bissau', 'ninja-forms' ) => 'GW',
		__( 'Guyana', 'ninja-forms' ) => 'GY',
		__( 'Haiti', 'ninja-forms' ) => 'HT',
		__( 'Heard y Mc Donald Islas', 'ninja-forms' ) => 'HM',
		__( 'Santa Sede (Ciudad del Vaticano)', 'ninja-forms' ) => 'VA',
		__( 'Honduras', 'ninja-forms' ) => 'HN',
		__( 'Hong Kong', 'ninja-forms' ) => 'HK',
		__( 'Hungria', 'ninja-forms' ) => 'HU',
		__( 'Islandia', 'ninja-forms' ) => 'IS',
		__( 'India', 'ninja-forms' ) => 'IN',
		__( 'Indonesia', 'ninja-forms' ) => 'ID',
		__( 'Iran (Islamic Republic Of)', 'ninja-forms' ) => 'IR',
		__( 'Irak', 'ninja-forms' ) => 'IQ',
		__( 'Irelanda', 'ninja-forms' ) => 'IE',
		__( 'Israel', 'ninja-forms' ) => 'IL',
		__( 'Italia', 'ninja-forms' ) => 'IT',
		__( 'Jamaica', 'ninja-forms' ) => 'JM',
		__( 'Japon', 'ninja-forms' ) => 'JP',
		__( 'Jordan', 'ninja-forms' ) => 'JO',
		__( 'Kazajstán', 'ninja-forms' ) => 'KZ',
		__( 'Kenia', 'ninja-forms' ) => 'KE',
		__( 'Kiribati', 'ninja-forms' ) => 'KI',
		__( 'República Democrática de Corea', 'ninja-forms' ) => 'KP',
		__( 'República de Corea', 'ninja-forms' ) => 'KR',
		__( 'Kuwait', 'ninja-forms' ) => 'KW',
		__( 'Kirguistán', 'ninja-forms' ) => 'KG',
		__( 'República de Laos', 'ninja-forms' ) => 'LA',
		__( 'Letonia', 'ninja-forms' ) => 'LV',
		__( 'Libano', 'ninja-forms' ) => 'LB',
		__( 'Lesoto', 'ninja-forms' ) => 'LS',
		__( 'Liberia', 'ninja-forms' ) => 'LR',
		__( 'Jamahiriya Árabe Libia', 'ninja-forms' ) => 'LY',
		__( 'Liechtenstein', 'ninja-forms' ) => 'LI',
		__( 'Lituania', 'ninja-forms' ) => 'LT',
		__( 'Luxembourg', 'ninja-forms' ) => 'LU',
		__( 'Macau', 'ninja-forms' ) => 'MO',
		__( 'Macedonia', 'ninja-forms' ) => 'MK',
		__( 'Madagascar', 'ninja-forms' ) => 'MG',
		__( 'Malawi', 'ninja-forms' ) => 'MW',
		__( 'Malasia', 'ninja-forms' ) => 'MY',
		__( 'Maldivia', 'ninja-forms' ) => 'MV',
		__( 'Mali', 'ninja-forms' ) => 'ML',
		__( 'Malta', 'ninja-forms' ) => 'MT',
		__( 'Islas Marshall', 'ninja-forms' ) => 'MH',
		__( 'Martinica', 'ninja-forms' ) => 'MQ',
		__( 'Mauritania', 'ninja-forms' ) => 'MR',
		__( 'Mauricio', 'ninja-forms' ) => 'MU',
		__( 'Mayotte', 'ninja-forms' ) => 'YT',
		__( 'México', 'ninja-forms' ) => 'MX',
		__( 'Micronesia', 'ninja-forms' ) => 'FM',
		__( 'Moldova', 'ninja-forms' ) => 'MD',
		__( 'Monaco', 'ninja-forms' ) => 'MC',
		__( 'Mongolia', 'ninja-forms' ) => 'MN',
		__( 'Montenegro', 'ninja-forms' ) => 'ME',
		__( 'Montserrat', 'ninja-forms' ) => 'MS',
		__( 'Marrueco', 'ninja-forms' ) => 'MA',
		__( 'Mozambique', 'ninja-forms' ) => 'MZ',
		__( 'Myanmar', 'ninja-forms' ) => 'MM',
		__( 'Namibia', 'ninja-forms' ) => 'NA',
		__( 'Nauru', 'ninja-forms' ) => 'NR',
		__( 'Nepal', 'ninja-forms' ) => 'NP',
		__( 'Países Bajos', 'ninja-forms' ) => 'NL',
		__( 'Antillas Holandesas', 'ninja-forms' ) => 'AN',
		__( 'Nueva Caledonia', 'ninja-forms' ) => 'NC',
		__( 'nueva Zelanda', 'ninja-forms' ) => 'NZ',
		__( 'Nicaragua', 'ninja-forms' ) => 'NI',
		__( 'Níger', 'ninja-forms' ) => 'NE',
		__( 'Nigeria', 'ninja-forms' ) => 'NG',
		__( 'Niue', 'ninja-forms' ) => 'NU',
		__( 'Isla Norfolk', 'ninja-forms' ) => 'NF',
		__( 'Islas Marianas del Norte', 'ninja-forms' ) => 'MP',
		__( 'Noruega', 'ninja-forms' ) => 'NO',
		__( 'Oman', 'ninja-forms' ) => 'OM',
		__( 'Pakistán', 'ninja-forms' ) => 'PK',
		__( 'Palau', 'ninja-forms' ) => 'PW',
		__( 'Panamá', 'ninja-forms' ) => 'PA',
		__( 'Papúa Nueva Guinea', 'ninja-forms' ) => 'PG',
		__( 'Paraguay', 'ninja-forms' ) => 'PY',
		__( 'Perú', 'ninja-forms' ) => 'PE',
		__( 'Filipinas', 'ninja-forms' ) => 'PH',
		__( 'Pitcairn', 'ninja-forms' ) => 'PN',
		__( 'Polonia', 'ninja-forms' ) => 'PL',
		__( 'Portugal', 'ninja-forms' ) => 'PT',
		__( 'Puerto Rico', 'ninja-forms' ) => 'PR',
		__( 'Qatar', 'ninja-forms' ) => 'QA',
		__( 'Reunion', 'ninja-forms' ) => 'RE',
		__( 'Románia', 'ninja-forms' ) => 'RO',
		__( 'Rusia', 'ninja-forms' ) => 'RU',
		__( 'Rwanda', 'ninja-forms' ) => 'RW',
		__( 'San Cristóbal y Nieves', 'ninja-forms' ) => 'KN',
		__( 'Santa Lucía', 'ninja-forms' ) => 'LC',
		__( 'San Vicente y las Granadinas', 'ninja-forms' ) => 'VC',
		__( 'Samoa', 'ninja-forms' ) => 'WS',
		__( 'San Marino', 'ninja-forms' ) => 'SM',
		__( 'Santo Tomé y Príncipe', 'ninja-forms' ) => 'ST',
		__( 'Arabia Saudita', 'ninja-forms' ) => 'SA',
		__( 'Senegal', 'ninja-forms' ) => 'SN',
		__( 'Serbia', 'ninja-forms' ) => 'RS',
		__( 'Seychelles', 'ninja-forms' ) => 'SC',
		__( 'Sierra Leona', 'ninja-forms' ) => 'SL',
		__( 'Singapore', 'ninja-forms' ) => 'SG',
		__( 'Eslovaquia (Slovak Republic)', 'ninja-forms' ) => 'SK',
		__( 'Eslovenia', 'ninja-forms' ) => 'SI',
		__( 'Islas Salomón', 'ninja-forms' ) => 'SB',
		__( 'Somalia', 'ninja-forms' ) => 'SO',
		__( 'Sudafrica', 'ninja-forms' ) => 'ZA',
		__( 'España', 'ninja-forms' ) => 'ES',
		__( 'Sri Lanka', 'ninja-forms' ) => 'LK',
		__( 'St. Helena', 'ninja-forms' ) => 'SH',
		__( 'St. Pierre And Miquelon', 'ninja-forms' ) => 'PM',
		__( 'Sudan', 'ninja-forms' ) => 'SD',
		__( 'Suriname', 'ninja-forms' ) => 'SR',
		__( 'Svalbard And Jan Mayen Islands', 'ninja-forms' ) => 'SJ',
		__( 'Swazilandia', 'ninja-forms' ) => 'SZ',
		__( 'Suecia', 'ninja-forms' ) => 'SE',
		__( 'Suiza', 'ninja-forms' ) => 'CH',
		__( 'Siria', 'ninja-forms' ) => 'SY',
		__( 'Taiwan', 'ninja-forms' ) => 'TW',
		__( 'Tajikistan', 'ninja-forms' ) => 'TJ',
		__( 'Tanzania', 'ninja-forms' ) => 'TZ',
		__( 'Tailandia', 'ninja-forms' ) => 'TH',
		__( 'Togo', 'ninja-forms' ) => 'TG',
		__( 'Tokelau', 'ninja-forms' ) => 'TK',
		__( 'Tonga', 'ninja-forms' ) => 'TO',
		__( 'Trinidad y Tobago', 'ninja-forms' ) => 'TT',
		__( 'Tunisia', 'ninja-forms' ) => 'TN',
		__( 'Turquia', 'ninja-forms' ) => 'TR',
		__( 'Turkmenistán', 'ninja-forms' ) => 'TM',
		__( 'Islas Turcas y Caicos', 'ninja-forms' ) => 'TC',
		__( 'Tuvalu', 'ninja-forms' ) => 'TV',
		__( 'Uganda', 'ninja-forms' ) => 'UG',
		__( 'Ucrania', 'ninja-forms' ) => 'UA',
		__( 'Emiratos Árabes Unidos', 'ninja-forms' ) => 'AE',
		__( 'Reino Unido', 'ninja-forms' ) => 'GB',
		__( 'Estados Unidos', 'ninja-forms' ) => 'US',
		__( 'Uruguay', 'ninja-forms' ) => 'UY',
		__( 'Uzbekistán', 'ninja-forms' ) => 'UZ',
		__( 'Vanuatu', 'ninja-forms' ) => 'VU',
		__( 'Venezuela', 'ninja-forms' ) => 'VE',
		__( 'Viet Nam', 'ninja-forms' ) => 'VN',
		__( 'Islas Virgenes (Británicas)', 'ninja-forms' ) => 'VG',
		__( 'Islas Virgenes (U.S.)', 'ninja-forms' ) => 'VI',
		__( 'Islas Wallis y Futuna', 'ninja-forms' ) => 'WF',
		__( 'Sáhara Occidental', 'ninja-forms' ) => 'EH',
		__( 'Yemen', 'ninja-forms' ) => 'YE',
		__( 'Yugoslavia', 'ninja-forms' ) => 'YU',
		__( 'Zambia', 'ninja-forms' ) => 'ZM',
		__( 'Zimbabwe', 'ninja-forms' ) => 'ZW'
	);

	$tmp_array = array();
	foreach ( $countries as $country => $abbr ) {
		$tmp_array[] = array( 'name' => $country, 'value' => $abbr );
	}
	$args = array(
		'name' => __( 'Country', 'ninja-forms' ),
		'sidebar' => '',
		'display_function' => 'ninja_forms_field_country_display',
		'group' => 'standard_fields',
		'edit_desc' => true,
		'edit_conditional' => true,
		'edit_options' => array(
			array(
				'type' => 'select',
				'name' => 'default_value',
				'label' => __( 'Default Country', 'ninja-forms' ),
				'class' => 'widefat',
				'options' => $tmp_array,
			),
			array(
				'type' => 'checkbox',
				'name' => 'country_use_custom_first',
				'label' => __( 'Use a custom first option', 'ninja-forms' ),
				'width' => 'thin',
			),
			array(
				'type' => 'text',
				'name' => 'country_custom_first',
				'label' => __( 'Custom first option', 'ninja-forms' ),
				'width' => 'thin',
				'class' => 'widefat',
			),
			array(
				'type' => 'hidden',
				'name' => 'user_info_field_group',
				'default' => 1,
			),
		),
		'conditional' => array(
			'value' => array(
				'type' => 'select',
				'options' => $countries,
			),
		),
	);

	ninja_forms_register_field( '_country', $args );
}

add_action( 'init', 'ninja_forms_register_field_country' );

/*
 * Function to display our country field on the front-end.
 *
 * @since 2.2.30
 * @returns void
 */

function ninja_forms_field_country_display( $field_id, $data, $form_id = '' ) {
	$countries = array(
		__( '- Seleccione', 'ninja-forms' ) => '',
		__( 'Afganistán', 'ninja-forms' ) => 'AF',
		__( 'Albania', 'ninja-forms' ) => 'AL',
		__( 'Argelia', 'ninja-forms' ) => 'DZ',
		__( 'Samoa Americana', 'ninja-forms' ) => 'AS',
		__( 'Andorra', 'ninja-forms' ) => 'AD',
		__( 'Angola', 'ninja-forms' ) => 'AO',
		__( 'Anguila', 'ninja-forms' ) => 'AI',
		__( 'Antártida', 'ninja-forms' ) => 'AQ',
		__( 'Antigua y Barbuda', 'ninja-forms' ) => 'AG',
		__( 'Argentina', 'ninja-forms' ) => 'AR',
		__( 'Armenia', 'ninja-forms' ) => 'AM',
		__( 'Aruba', 'ninja-forms' ) => 'AW',
		__( 'Australia', 'ninja-forms' ) => 'AU',
		__( 'Austria', 'ninja-forms' ) => 'AT',
		__( 'Azerbaiyán', 'ninja-forms' ) => 'AZ',
		__( 'Bahamas', 'ninja-forms' ) => 'BS',
		__( 'Bahrein', 'ninja-forms' ) => 'BH',
		__( 'Bangladesh', 'ninja-forms' ) => 'BD',
		__( 'Barbados', 'ninja-forms' ) => 'BB',
		__( 'Bielorrusia', 'ninja-forms' ) => 'BY',
		__( 'Bélgica', 'ninja-forms' ) => 'BE',
		__( 'Belice', 'ninja-forms' ) => 'BZ',
		__( 'Benin', 'ninja-forms' ) => 'BJ',
		__( 'Bermuda', 'ninja-forms' ) => 'BM',
		__( 'Bután', 'ninja-forms' ) => 'BT',
		__( 'Bolivia', 'ninja-forms' ) => 'BO',
		__( 'Bosnia y Herzegovina', 'ninja-forms' ) => 'BA',
		__( 'Botswana', 'ninja-forms' ) => 'BW',
		__( 'Isla Bouvet', 'ninja-forms' ) => 'BV',
		__( 'Brasil', 'ninja-forms' ) => 'BR',
		__( 'Territorio Británico del Océano Índico', 'ninja-forms' ) => 'IO',
		__( 'Brunei Darussalam', 'ninja-forms' ) => 'BN',
		__( 'Bulgaria', 'ninja-forms' ) => 'BG',
		__( 'Burkina Faso', 'ninja-forms' ) => 'BF',
		__( 'Burundi', 'ninja-forms' ) => 'BI',
		__( 'Camboya', 'ninja-forms' ) => 'KH',
		__( 'Camerún', 'ninja-forms' ) => 'CM',
		__( 'Canadá', 'ninja-forms' ) => 'CA',
		__( 'Cabo Verde', 'ninja-forms' ) => 'CV',
		__( 'Islas Caimán', 'ninja-forms' ) => 'KY',
		__( 'República Centroafricana', 'ninja-forms' ) => 'CF',
		__( 'Chad', 'ninja-forms' ) => 'TD',
		__( 'Chile', 'ninja-forms' ) => 'CL',
		__( 'China', 'ninja-forms' ) => 'CN',
		__( 'Isla de Navidad', 'ninja-forms' ) => 'CX',
		__( 'Cocos (Keeling) Islands', 'ninja-forms' ) => 'CC',
		__( 'Colombia', 'ninja-forms' ) => 'CO',
		__( 'Comoras', 'ninja-forms' ) => 'KM',
		__( 'Congo', 'ninja-forms' ) => 'CG',
		__( 'La República Democrática del Congo', 'ninja-forms' ) => 'CD',
		__( 'Islas Cook', 'ninja-forms' ) => 'CK',
		__( 'Costa Rica', 'ninja-forms' ) => 'CR',
		__( 'Costa de Marfil', 'ninja-forms' ) => 'CI',
		__( 'Croacia', 'ninja-forms' ) => 'HR',
		__( 'Cuba', 'ninja-forms' ) => 'CU',
		__( 'Chipre', 'ninja-forms' ) => 'CY',
		__( 'República Checa', 'ninja-forms' ) => 'CZ',
		__( 'Dinamarca', 'ninja-forms' ) => 'DK',
		__( 'Djibouti', 'ninja-forms' ) => 'DJ',
		__( 'Dominica', 'ninja-forms' ) => 'DM',
		__( 'República Dominicana', 'ninja-forms' ) => 'DO',
		__( 'Timor Oriental', 'ninja-forms' ) => 'TL',
		__( 'Ecuador', 'ninja-forms' ) => 'EC',
		__( 'Egipto', 'ninja-forms' ) => 'EG',
		__( 'El Salvador', 'ninja-forms' ) => 'SV',
		__( 'Guinea Ecuatorial', 'ninja-forms' ) => 'GQ',
		__( 'Eritrea', 'ninja-forms' ) => 'ER',
		__( 'Estonia', 'ninja-forms' ) => 'EE',
		__( 'Etiopía', 'ninja-forms' ) => 'ET',
		__( 'Islas Malvinas', 'ninja-forms' ) => 'FK',
		__( 'Islas Feroe', 'ninja-forms' ) => 'FO',
		__( 'Fiji', 'ninja-forms' ) => 'FJ',
		__( 'Finlandia', 'ninja-forms' ) => 'FI',
		__( 'Francia', 'ninja-forms' ) => 'FR',
		__( 'Guayana francés', 'ninja-forms' ) => 'GF',
		__( 'Polinesia francés', 'ninja-forms' ) => 'PF',
		__( 'Territorios Franceses del Sur', 'ninja-forms' ) => 'TF',
		__( 'Gabón', 'ninja-forms' ) => 'GA',
		__( 'Gambia', 'ninja-forms' ) => 'GM',
		__( 'Georgia', 'ninja-forms' ) => 'GE',
		__( 'Alemania', 'ninja-forms' ) => 'DE',
		__( 'Ghana', 'ninja-forms' ) => 'GH',
		__( 'Gibraltar', 'ninja-forms' ) => 'GI',
		__( 'Grecia', 'ninja-forms' ) => 'GR',
		__( 'Groenlandia', 'ninja-forms' ) => 'GL',
		__( 'Granada', 'ninja-forms' ) => 'GD',
		__( 'Guadeloupe', 'ninja-forms' ) => 'GP',
		__( 'Guam', 'ninja-forms' ) => 'GU',
		__( 'Guatemala', 'ninja-forms' ) => 'GT',
		__( 'Guinea', 'ninja-forms' ) => 'GN',
		__( 'Guinea-Bissau', 'ninja-forms' ) => 'GW',
		__( 'Guyana', 'ninja-forms' ) => 'GY',
		__( 'Haiti', 'ninja-forms' ) => 'HT',
		__( 'Heard y Mc Donald Islas', 'ninja-forms' ) => 'HM',
		__( 'Santa Sede (Ciudad del Vaticano)', 'ninja-forms' ) => 'VA',
		__( 'Honduras', 'ninja-forms' ) => 'HN',
		__( 'Hong Kong', 'ninja-forms' ) => 'HK',
		__( 'Hungria', 'ninja-forms' ) => 'HU',
		__( 'Islandia', 'ninja-forms' ) => 'IS',
		__( 'India', 'ninja-forms' ) => 'IN',
		__( 'Indonesia', 'ninja-forms' ) => 'ID',
		__( 'Iran (Islamic Republic Of)', 'ninja-forms' ) => 'IR',
		__( 'Irak', 'ninja-forms' ) => 'IQ',
		__( 'Irelanda', 'ninja-forms' ) => 'IE',
		__( 'Israel', 'ninja-forms' ) => 'IL',
		__( 'Italia', 'ninja-forms' ) => 'IT',
		__( 'Jamaica', 'ninja-forms' ) => 'JM',
		__( 'Japon', 'ninja-forms' ) => 'JP',
		__( 'Jordan', 'ninja-forms' ) => 'JO',
		__( 'Kazajstán', 'ninja-forms' ) => 'KZ',
		__( 'Kenia', 'ninja-forms' ) => 'KE',
		__( 'Kiribati', 'ninja-forms' ) => 'KI',
		__( 'República Democrática de Corea', 'ninja-forms' ) => 'KP',
		__( 'República de Corea', 'ninja-forms' ) => 'KR',
		__( 'Kuwait', 'ninja-forms' ) => 'KW',
		__( 'Kirguistán', 'ninja-forms' ) => 'KG',
		__( 'República de Laos', 'ninja-forms' ) => 'LA',
		__( 'Letonia', 'ninja-forms' ) => 'LV',
		__( 'Libano', 'ninja-forms' ) => 'LB',
		__( 'Lesoto', 'ninja-forms' ) => 'LS',
		__( 'Liberia', 'ninja-forms' ) => 'LR',
		__( 'Jamahiriya Árabe Libia', 'ninja-forms' ) => 'LY',
		__( 'Liechtenstein', 'ninja-forms' ) => 'LI',
		__( 'Lituania', 'ninja-forms' ) => 'LT',
		__( 'Luxembourg', 'ninja-forms' ) => 'LU',
		__( 'Macau', 'ninja-forms' ) => 'MO',
		__( 'Macedonia', 'ninja-forms' ) => 'MK',
		__( 'Madagascar', 'ninja-forms' ) => 'MG',
		__( 'Malawi', 'ninja-forms' ) => 'MW',
		__( 'Malasia', 'ninja-forms' ) => 'MY',
		__( 'Maldivia', 'ninja-forms' ) => 'MV',
		__( 'Mali', 'ninja-forms' ) => 'ML',
		__( 'Malta', 'ninja-forms' ) => 'MT',
		__( 'Islas Marshall', 'ninja-forms' ) => 'MH',
		__( 'Martinica', 'ninja-forms' ) => 'MQ',
		__( 'Mauritania', 'ninja-forms' ) => 'MR',
		__( 'Mauricio', 'ninja-forms' ) => 'MU',
		__( 'Mayotte', 'ninja-forms' ) => 'YT',
		__( 'México', 'ninja-forms' ) => 'MX',
		__( 'Micronesia', 'ninja-forms' ) => 'FM',
		__( 'Moldova', 'ninja-forms' ) => 'MD',
		__( 'Monaco', 'ninja-forms' ) => 'MC',
		__( 'Mongolia', 'ninja-forms' ) => 'MN',
		__( 'Montenegro', 'ninja-forms' ) => 'ME',
		__( 'Montserrat', 'ninja-forms' ) => 'MS',
		__( 'Marrueco', 'ninja-forms' ) => 'MA',
		__( 'Mozambique', 'ninja-forms' ) => 'MZ',
		__( 'Myanmar', 'ninja-forms' ) => 'MM',
		__( 'Namibia', 'ninja-forms' ) => 'NA',
		__( 'Nauru', 'ninja-forms' ) => 'NR',
		__( 'Nepal', 'ninja-forms' ) => 'NP',
		__( 'Países Bajos', 'ninja-forms' ) => 'NL',
		__( 'Antillas Holandesas', 'ninja-forms' ) => 'AN',
		__( 'Nueva Caledonia', 'ninja-forms' ) => 'NC',
		__( 'nueva Zelanda', 'ninja-forms' ) => 'NZ',
		__( 'Nicaragua', 'ninja-forms' ) => 'NI',
		__( 'Níger', 'ninja-forms' ) => 'NE',
		__( 'Nigeria', 'ninja-forms' ) => 'NG',
		__( 'Niue', 'ninja-forms' ) => 'NU',
		__( 'Isla Norfolk', 'ninja-forms' ) => 'NF',
		__( 'Islas Marianas del Norte', 'ninja-forms' ) => 'MP',
		__( 'Noruega', 'ninja-forms' ) => 'NO',
		__( 'Oman', 'ninja-forms' ) => 'OM',
		__( 'Pakistán', 'ninja-forms' ) => 'PK',
		__( 'Palau', 'ninja-forms' ) => 'PW',
		__( 'Panamá', 'ninja-forms' ) => 'PA',
		__( 'Papúa Nueva Guinea', 'ninja-forms' ) => 'PG',
		__( 'Paraguay', 'ninja-forms' ) => 'PY',
		__( 'Perú', 'ninja-forms' ) => 'PE',
		__( 'Filipinas', 'ninja-forms' ) => 'PH',
		__( 'Pitcairn', 'ninja-forms' ) => 'PN',
		__( 'Polonia', 'ninja-forms' ) => 'PL',
		__( 'Portugal', 'ninja-forms' ) => 'PT',
		__( 'Puerto Rico', 'ninja-forms' ) => 'PR',
		__( 'Qatar', 'ninja-forms' ) => 'QA',
		__( 'Reunion', 'ninja-forms' ) => 'RE',
		__( 'Románia', 'ninja-forms' ) => 'RO',
		__( 'Rusia', 'ninja-forms' ) => 'RU',
		__( 'Rwanda', 'ninja-forms' ) => 'RW',
		__( 'San Cristóbal y Nieves', 'ninja-forms' ) => 'KN',
		__( 'Santa Lucía', 'ninja-forms' ) => 'LC',
		__( 'San Vicente y las Granadinas', 'ninja-forms' ) => 'VC',
		__( 'Samoa', 'ninja-forms' ) => 'WS',
		__( 'San Marino', 'ninja-forms' ) => 'SM',
		__( 'Santo Tomé y Príncipe', 'ninja-forms' ) => 'ST',
		__( 'Arabia Saudita', 'ninja-forms' ) => 'SA',
		__( 'Senegal', 'ninja-forms' ) => 'SN',
		__( 'Serbia', 'ninja-forms' ) => 'RS',
		__( 'Seychelles', 'ninja-forms' ) => 'SC',
		__( 'Sierra Leona', 'ninja-forms' ) => 'SL',
		__( 'Singapore', 'ninja-forms' ) => 'SG',
		__( 'Eslovaquia (Slovak Republic)', 'ninja-forms' ) => 'SK',
		__( 'Eslovenia', 'ninja-forms' ) => 'SI',
		__( 'Islas Salomón', 'ninja-forms' ) => 'SB',
		__( 'Somalia', 'ninja-forms' ) => 'SO',
		__( 'Sudafrica', 'ninja-forms' ) => 'ZA',
		__( 'España', 'ninja-forms' ) => 'ES',
		__( 'Sri Lanka', 'ninja-forms' ) => 'LK',
		__( 'St. Helena', 'ninja-forms' ) => 'SH',
		__( 'St. Pierre And Miquelon', 'ninja-forms' ) => 'PM',
		__( 'Sudan', 'ninja-forms' ) => 'SD',
		__( 'Suriname', 'ninja-forms' ) => 'SR',
		__( 'Svalbard And Jan Mayen Islands', 'ninja-forms' ) => 'SJ',
		__( 'Swazilandia', 'ninja-forms' ) => 'SZ',
		__( 'Suecia', 'ninja-forms' ) => 'SE',
		__( 'Suiza', 'ninja-forms' ) => 'CH',
		__( 'Siria', 'ninja-forms' ) => 'SY',
		__( 'Taiwan', 'ninja-forms' ) => 'TW',
		__( 'Tajikistan', 'ninja-forms' ) => 'TJ',
		__( 'Tanzania', 'ninja-forms' ) => 'TZ',
		__( 'Tailandia', 'ninja-forms' ) => 'TH',
		__( 'Togo', 'ninja-forms' ) => 'TG',
		__( 'Tokelau', 'ninja-forms' ) => 'TK',
		__( 'Tonga', 'ninja-forms' ) => 'TO',
		__( 'Trinidad y Tobago', 'ninja-forms' ) => 'TT',
		__( 'Tunisia', 'ninja-forms' ) => 'TN',
		__( 'Turquia', 'ninja-forms' ) => 'TR',
		__( 'Turkmenistán', 'ninja-forms' ) => 'TM',
		__( 'Islas Turcas y Caicos', 'ninja-forms' ) => 'TC',
		__( 'Tuvalu', 'ninja-forms' ) => 'TV',
		__( 'Uganda', 'ninja-forms' ) => 'UG',
		__( 'Ucrania', 'ninja-forms' ) => 'UA',
		__( 'Emiratos Árabes Unidos', 'ninja-forms' ) => 'AE',
		__( 'Reino Unido', 'ninja-forms' ) => 'GB',
		__( 'Estados Unidos', 'ninja-forms' ) => 'US',
		__( 'Uruguay', 'ninja-forms' ) => 'UY',
		__( 'Uzbekistán', 'ninja-forms' ) => 'UZ',
		__( 'Vanuatu', 'ninja-forms' ) => 'VU',
		__( 'Venezuela', 'ninja-forms' ) => 'VE',
		__( 'Viet Nam', 'ninja-forms' ) => 'VN',
		__( 'Islas Virgenes (Británicas)', 'ninja-forms' ) => 'VG',
		__( 'Islas Virgenes (U.S.)', 'ninja-forms' ) => 'VI',
		__( 'Islas Wallis y Futuna', 'ninja-forms' ) => 'WF',
		__( 'Sáhara Occidental', 'ninja-forms' ) => 'EH',
		__( 'Yemen', 'ninja-forms' ) => 'YE',
		__( 'Yugoslavia', 'ninja-forms' ) => 'YU',
		__( 'Zambia', 'ninja-forms' ) => 'ZM',
		__( 'Zimbabwe', 'ninja-forms' ) => 'ZW'
	);

	if( isset( $data['default_value'] ) ) {
		$default_value = $data['default_value'];
	}else{
		$default_value = '';
	}

	if ( isset ( $data['country_custom_first'] ) ) {
		$country_custom_first = $data['country_custom_first'];
	} else {
		$country_custom_first = '';
	}

	if ( isset ( $data['country_use_custom_first'] ) AND $data['country_use_custom_first'] == 1 ) {
		$countries = array_merge( array( $country_custom_first => '' ), $countries );
	}

	$field_class = ninja_forms_get_field_class( $field_id, $form_id );
	?>

	<input type="hidden" id="ninja_forms_field_<?php echo $field_id;?>_list_type" value="dropdown">
	<select name="ninja_forms_field_<?php echo $field_id;?>" id="ninja_forms_field_<?php echo $field_id;?>" rel="<?php echo $field_id;?>" class="<?php echo $field_class;?>">
		<?php
		foreach ( $countries as $country => $abbr ) {
			?>
			<option value="<?php echo $abbr;?>" <?php selected( $abbr, $default_value );?>><?php echo $country;?></option>
			<?php
		}
	?>
	</select>

	<?php
}

/*
 *
 * Function that filters the hidden field output by display that identifies the field type.
 * This is a work around and will need to be removed once proper field registration is in place.
 *
 * @since 2.2.30
 * @returns string $field_type
 */

function ninja_forms_field_country_type_filter( $field_type, $field_id ) {
	$field = ninja_forms_get_field_by_id( $field_id );
	if ( $field['type'] == '_country' ) {
		$field_type = 'list';
	}

	return $field_type;
}

add_action( 'ninja_forms_display_field_type', 'ninja_forms_field_country_type_filter', 10, 2 );